[package]
name = "pandemic_simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
bevy = { version = "0.6", default-features = false, features = ["bevy_winit"] }
bevy_prototype_lyon = "0.4"