[package]
name = "kvs"
version = "0.1.0"
authors = ["pj_zhong <pj_zhong@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"


[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"